Repository tensorflow/tflite-micro-arduino-examples, pull requests merged in 2021-08, with the labels that each got.

#4 Arduino python scripts
  scripts/MANIFEST.ini
  scripts/create_tflm_arduino.py
  scripts/fix_arduino_subfolders.py
  scripts/helper_functions.sh
  scripts/install_arduino_cli.sh
  scripts/test_arduino_library.sh
  scripts/transform_source.py
Labels: bug, cla: yes

#5 Arduino file tree
  .gitignore
  examples/hello_world/constants.cpp
  examples/hello_world/constants.h
  examples/hello_world/hello_world.ino
  examples/hello_world/main.cpp
  examples/hello_world/main_functions.h
  examples/hello_world/model.cpp
  examples/hello_world/model.h
  examples/hello_world/output_handler.cpp
  examples/hello_world/output_handler.h
  examples/magic_wand/accelerometer_handler.cpp
  examples/magic_wand/accelerometer_handler.h
  examples/magic_wand/constants.h
  examples/magic_wand/gesture_predictor.cpp
  examples/magic_wand/gesture_predictor.h
  examples/magic_wand/magic_wand.ino
  examples/magic_wand/magic_wand_model_data.cpp
  examples/magic_wand/magic_wand_model_data.h
  examples/magic_wand/main.cpp
  examples/magic_wand/main_functions.h
  examples/magic_wand/output_handler.cpp
  examples/magic_wand/output_handler.h
  examples/micro_speech/audio_provider.cpp
  examples/micro_speech/audio_provider.h
  examples/micro_speech/command_responder.cpp
  examples/micro_speech/command_responder.h
  examples/micro_speech/feature_provider.cpp
  examples/micro_speech/feature_provider.h
  examples/micro_speech/main.cpp
  examples/micro_speech/main_functions.h
  examples/micro_speech/micro_features_micro_features_generator.cpp
  examples/micro_speech/micro_features_micro_features_generator.h
  examples/micro_speech/micro_features_micro_model_settings.cpp
  examples/micro_speech/micro_features_micro_model_settings.h
  examples/micro_speech/micro_features_model.cpp
  examples/micro_speech/micro_features_model.h
  examples/micro_speech/micro_features_no_micro_features_data.cpp
  examples/micro_speech/micro_features_no_micro_features_data.h
  examples/micro_speech/micro_features_yes_micro_features_data.cpp
  examples/micro_speech/micro_features_yes_micro_features_data.h
  examples/micro_speech/micro_speech.ino
  examples/micro_speech/recognize_commands.cpp
  examples/micro_speech/recognize_commands.h
  examples/person_detection/detection_responder.cpp
  examples/person_detection/detection_responder.h
  examples/person_detection/image_provider.cpp
  examples/person_detection/image_provider.h
  examples/person_detection/main.cpp
  examples/person_detection/main_functions.h
  examples/person_detection/model_settings.cpp
  examples/person_detection/model_settings.h
  examples/person_detection/person_detect_model_data.h
  examples/person_detection/person_detection.ino
  library.properties
  src/TensorFlowLite.h
  src/tensorflow/lite/micro/debug_log.cpp
  src/tensorflow/lite/micro/system_setup.cpp
Labels: bug, cla: yes

#7 Add end-to-end tree creation and build test script
  scripts/create_tflm_arduino.py
  scripts/test_tflm_arduino.sh
Labels: bug, cla: yes

#11 Add missing repo recreation script
  scripts/recreate_repo_tree.sh
Labels: bug, cla: yes

#10 Add missing test script
  scripts/test_repo_tree.sh
Labels: bug, cla: yes

#12 Setting up workflows to sync code and test the Arduino build.
  .github/workflows/ci.yml
  .github/workflows/sync.yml
  scripts/sync_from_tflite_micro.sh
  scripts/test_repo_tree.sh
Labels: ci:run, cla: yes

#13 Added temporary workflow to test the sync script via PR labels.
  .github/workflows/sync_test.yml
Labels: ci:run, cla: yes

#14 Fixes to synchronize repo
  .github/workflows/sync.yml
  scripts/create_tflm_arduino.py
Labels: bug, cla: yes

#16 Clean up the workflow files
  .github/workflows/sync.yml
  .github/workflows/sync_test.yml
Labels: cla: yes

#17 More improvements to the github workflows.
  .github/workflows/remove-labels.yml
  .github/workflows/sync.yml
Labels: cla: yes

#18 update branch name
  .github/workflows/sync.yml
Labels: cla: yes

#20 getting some initial documentation in place.
  .gitignore
  README.md
  docs/hello_world_screenshot.png
Labels: cla: yes

#22 Add ARDUINO defines
  scripts/MANIFEST.ini
  scripts/create_tflm_arduino.py
Labels: bug, cla: yes

#24 Added build badges to readme
  README.md
Labels: cla: yes

#25 Support cortex_m_generic target
  scripts/MANIFEST.ini
  scripts/sync_from_tflite_micro.sh
  scripts/test_tflm_arduino.sh
Labels: bug, cla: yes

#26 Update build badges.
  README.md
Labels: cla: yes

#27 Update sync script based on https://github.com/tensorflow/tflite-micro/pull/385
  scripts/sync_from_tflite_micro.sh
Labels: cla: yes

#30 Add README for create_tflm_arduino.py script
  scripts/README_create_tflm_arduino.md
Labels: cla: yes

#31 Fixes to the sync script
  scripts/MANIFEST.ini
Labels: cla: yes

#32 Update examples from tflite-micro with the following steps:
  examples/hello_world/arduino_constants.cpp
  examples/hello_world/arduino_main.cpp
  examples/hello_world/arduino_output_handler.cpp
  examples/magic_wand/arduino_accelerometer_handler.cpp
  examples/magic_wand/arduino_main.cpp
  examples/magic_wand/arduino_output_handler.cpp
  examples/magic_wand/sparkfun_edge_accelerometer_handler.cpp
  examples/magic_wand/sparkfun_edge_output_handler.cpp
  examples/micro_speech/arduino_audio_provider.cpp
  examples/micro_speech/arduino_command_responder.cpp
  examples/micro_speech/arduino_main.cpp
  examples/micro_speech/sparkfun_edge_audio_provider.cpp
  examples/micro_speech/sparkfun_edge_command_responder.cpp
  examples/person_detection/arduino_HM01B0_platform.h
  examples/person_detection/arduino_detection_responder.cpp
  examples/person_detection/arduino_image_provider.cpp
  examples/person_detection/arduino_main.cpp
  examples/person_detection/himax_driver_HM01B0.c
  examples/person_detection/himax_driver_HM01B0.h
  examples/person_detection/himax_driver_HM01B0_RAW8_QVGA_8bits_lsb_5fps.h
  examples/person_detection/himax_driver_HM01B0_Walking1s_01.h
  examples/person_detection/himax_driver_HM01B0_debug.c
  examples/person_detection/himax_driver_HM01B0_debug.h
  examples/person_detection/himax_driver_HM01B0_optimized.c
  examples/person_detection/himax_driver_HM01B0_optimized.h
  examples/person_detection/sparkfun_edge_detection_responder.cpp
  examples/person_detection/sparkfun_edge_image_provider.cpp
  scripts/MANIFEST.ini
Labels: cla: yes

#34 Remove upstream person_detect_model_data as part of the sync.
  scripts/MANIFEST.ini
Labels: cla: yes

#35 Update sync script for the new location of the models in tflite-micro
  .github/workflows/sync.yml
  scripts/MANIFEST.ini
Labels: cla: yes

#37 Updated README
  README.md
Labels: cla: yes

#41 Install Wave in preparation for https://github.com/tensorflow/tflite-micro/pull/429/
  .github/workflows/sync.yml
Labels: cla: yes
